name: 'Setup Rust Environment'
description: 'Setup Rust toolchain with caching'
inputs:
  components:
    description: 'Rust components to install (rustfmt, clippy)'
    required: false
    default: ''
  targets:
    description: 'Additional targets to install'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Cache Rust dependencies
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
        shared-key: 'rust-${{ runner.os }}'