name: 'Setup System Dependencies'
description: 'Install platform-specific system dependencies for Tauri'
runs:
  using: 'composite'
  steps:
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libglib2.0-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          patchelf \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libxdo-dev \
          pkg-config

    - name: Setup Xcode (macOS only)
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable