name: Conventional Commits Check

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, edited]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Install dependencies
        run: |
          npm ci --include=dev || npm install --include=dev
      
      - name: Check commit messages
        run: |
          # Get the range of commits for this PR
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          
          echo "Checking commits from $BASE_SHA to $HEAD_SHA"
          
          # Check each commit in the PR
          git log --format="%H %s" $BASE_SHA..$HEAD_SHA | while read commit_hash commit_message; do
            echo "Checking commit: $commit_hash - $commit_message"
            echo "$commit_message" | npx commitlint --config ./commitlint.config.js || exit 1
          done
      
      - name: Check PR title (optional but recommended)
        if: always()
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.title }}" | npx commitlint --config ./commitlint.config.js || echo "⚠️ PR title doesn't follow conventional commits format (non-blocking)"